[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quota_manager"
version = "0.1.0"
description = ""
authors = [
    { name = "Ambroise", email = "ambroisecuru@gmail.com" }
]

[project.scripts]
quota_manager = "quota_manager.cli:main"